from collections.abc import Iterable
from contextlib import AbstractContextManager
from typing import Protocol

from shopdb.core.dataset.context import SeedContext


class SeedSession(Protocol):
    def has_triggers(self) -> bool: ...
    def has_data(self) -> bool: ...
    def truncate(self) -> None: ...
    def load_static(self, ctx: SeedContext) -> dict[str, int]: ...
    def reset_sequences(self) -> int: ...


class SeedStore(Protocol):
    def session(self) -> AbstractContextManager[SeedSession]: ...


class WorkerPool(Protocol):
    def open(self, ctx: SeedContext, workers: int) -> AbstractContextManager["WorkerPool"]: ...
    def run(
        self, tasks: list[tuple[str, int, int, int]]
    ) -> Iterable[tuple[str, int, dict[str, int], float]]: ...
