-- 010_reference.sql
-- Small lookup tables (profile S). Rows are inserted by the seeder, not here.
-- Every schema file runs as shop_owner so the schema owns what it creates, not the superuser.

SET ROLE shop_owner;

CREATE TABLE shop.countries (
    country_code char(2) PRIMARY KEY,
    name         text NOT NULL,
    region       text NOT NULL
);
COMMENT ON TABLE shop.countries IS 'ISO 3166 countries referenced by addresses, suppliers and warehouses.';

CREATE TABLE shop.currencies (
    currency_code char(3) PRIMARY KEY,
    name          text NOT NULL,
    minor_units   smallint NOT NULL DEFAULT 2
);
COMMENT ON TABLE shop.currencies IS 'ISO 4217 currencies. minor_units is the number of decimal places.';

CREATE TABLE shop.order_statuses (
    status_id   smallint PRIMARY KEY,
    code        text NOT NULL UNIQUE,
    description text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false
);
COMMENT ON TABLE shop.order_statuses IS 'Order lifecycle states (pending, paid, shipped, ...).';
COMMENT ON COLUMN shop.order_statuses.is_terminal IS 'True when no further transition is allowed (delivered, cancelled, refunded).';

CREATE TABLE shop.payment_methods (
    payment_method_id smallint PRIMARY KEY,
    code              text NOT NULL UNIQUE,
    name              text NOT NULL,
    is_active         boolean NOT NULL DEFAULT true
);
COMMENT ON TABLE shop.payment_methods IS 'Supported ways to pay (card, paypal, bank transfer, ...).';

CREATE TABLE shop.categories (
    category_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   int REFERENCES shop.categories (category_id),
    name        text NOT NULL,
    slug        text NOT NULL UNIQUE
);
COMMENT ON TABLE shop.categories IS 'Product category tree. parent_id is NULL for top-level categories.';
