-- 020_core.sql
-- Core business entities: tenants, customers, addresses, catalog, suppliers, warehouses, staff.
--
-- Primary keys are GENERATED BY DEFAULT AS IDENTITY: the seeder can insert explicit ids with COPY, and
-- procedures/application code can let the database assign them. After a bulk load the seeder must
-- advance each identity sequence past the largest loaded id.
--
-- Only PRIMARY KEY and UNIQUE indexes are created here. Other indexes are added after the data load
-- (db/post_load/100_indexes.sql), and some are left out on purpose (see docs/planted-problems.md).

SET ROLE shop_owner;

CREATE TABLE shop.tenants (
    tenant_id  int PRIMARY KEY,
    name       text NOT NULL,
    plan       text NOT NULL DEFAULT 'standard' CHECK (plan IN ('free', 'standard', 'enterprise')),
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.tenants IS 'Merchants using the platform. Customers, orders and payments are isolated per tenant by row-level security.';

CREATE TABLE shop.customers (
    customer_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        int NOT NULL REFERENCES shop.tenants (tenant_id),
    email            text NOT NULL,
    first_name       text NOT NULL,
    last_name        text NOT NULL,
    phone            text,
    tier             text NOT NULL DEFAULT 'standard' CHECK (tier IN ('standard', 'silver', 'gold', 'platinum')),
    order_count      int NOT NULL DEFAULT 0,
    marketing_opt_in boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz,
    UNIQUE (tenant_id, email)
);
COMMENT ON TABLE shop.customers IS 'Shoppers. Soft-deleted rows keep deleted_at set and stay in the table (planted problem P06). RLS: filtered by tenant_id.';
COMMENT ON COLUMN shop.customers.order_count IS 'Denormalized count of orders, maintained by a trigger (contention hot spot).';
COMMENT ON COLUMN shop.customers.tier IS 'Loyalty tier, recalculated by the recalc_customer_tiers procedure.';
COMMENT ON COLUMN shop.customers.deleted_at IS 'Soft delete marker; NULL means active.';

CREATE TABLE shop.addresses (
    address_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  bigint NOT NULL REFERENCES shop.customers (customer_id),
    kind         text NOT NULL DEFAULT 'shipping' CHECK (kind IN ('shipping', 'billing')),
    line1        text NOT NULL,
    line2        text,
    city         text NOT NULL,
    region       text,
    postal_code  text NOT NULL,
    country_code char(2) NOT NULL REFERENCES shop.countries (country_code),
    is_default   boolean NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.addresses IS 'Shipping and billing addresses owned by a customer.';

CREATE TABLE shop.suppliers (
    supplier_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text NOT NULL,
    country_code   char(2) NOT NULL REFERENCES shop.countries (country_code),
    contact_email  text,
    lead_time_days smallint NOT NULL DEFAULT 14,
    rating         numeric(3, 2) CHECK (rating BETWEEN 0 AND 5),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.suppliers IS 'Companies that supply products.';

CREATE TABLE shop.warehouses (
    warehouse_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text NOT NULL UNIQUE,
    country_code   char(2) NOT NULL REFERENCES shop.countries (country_code),
    city           text NOT NULL,
    capacity_units int NOT NULL CHECK (capacity_units > 0)
);
COMMENT ON TABLE shop.warehouses IS 'Fulfilment centres that hold inventory and ship orders.';

CREATE TABLE shop.employees (
    employee_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id smallint REFERENCES shop.warehouses (warehouse_id),
    manager_id   int REFERENCES shop.employees (employee_id),
    full_name    text NOT NULL,
    email        text NOT NULL UNIQUE,
    role         text NOT NULL,
    hired_at     date NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.employees IS 'Internal staff. manager_id forms a reporting tree; warehouse_id is NULL for office staff.';

CREATE TABLE shop.products (
    product_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id   int NOT NULL REFERENCES shop.suppliers (supplier_id),
    category_id   int NOT NULL REFERENCES shop.categories (category_id),
    sku           text NOT NULL UNIQUE,
    name          text NOT NULL,
    description   text,
    brand         text,
    base_price    numeric(10, 2) NOT NULL CHECK (base_price >= 0),
    currency_code char(3) NOT NULL REFERENCES shop.currencies (currency_code),
    attributes    jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_active     boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz
);
COMMENT ON TABLE shop.products IS 'Catalog items. name/description are searched with LIKE ''%x%'' and have no trigram index (planted problem P04).';
COMMENT ON COLUMN shop.products.attributes IS 'Large free-form JSONB document; frequent updates cause table bloat (planted problem P05).';

CREATE TABLE shop.product_variants (
    variant_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   int NOT NULL REFERENCES shop.products (product_id),
    sku          text NOT NULL UNIQUE,
    size         text,
    color        text,
    weight_grams int,
    price_delta  numeric(10, 2) NOT NULL DEFAULT 0,
    barcode      text,
    is_active    boolean NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.product_variants IS 'Sellable versions of a product (size/colour). Inventory and order lines refer to variants.';
