-- 030_orders.sql
-- Transactional tables: carts, orders, order lines, payments, shipments, invoices, refunds.
-- Money columns use numeric (never float). Timestamps are timestamptz.

SET ROLE shop_owner;

CREATE TABLE shop.carts (
    cart_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES shop.customers (customer_id),
    status      text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'converted', 'abandoned')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz
);
COMMENT ON TABLE shop.carts IS 'Shopping carts. High churn: rows are created, updated and abandoned constantly.';

CREATE TABLE shop.orders (
    order_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           int NOT NULL REFERENCES shop.tenants (tenant_id),
    customer_id         bigint NOT NULL REFERENCES shop.customers (customer_id),
    status_id           smallint NOT NULL REFERENCES shop.order_statuses (status_id),
    order_number        text NOT NULL UNIQUE,
    channel             text NOT NULL DEFAULT 'web' CHECK (channel IN ('web', 'mobile', 'store', 'api')),
    currency_code       char(3) NOT NULL REFERENCES shop.currencies (currency_code),
    subtotal            numeric(12, 2) NOT NULL CHECK (subtotal >= 0),
    tax_amount          numeric(12, 2) NOT NULL DEFAULT 0,
    shipping_amount     numeric(12, 2) NOT NULL DEFAULT 0,
    discount_amount     numeric(12, 2) NOT NULL DEFAULT 0,
    total_amount        numeric(12, 2) NOT NULL CHECK (total_amount >= 0),
    shipping_address_id bigint REFERENCES shop.addresses (address_id),
    billing_address_id  bigint REFERENCES shop.addresses (address_id),
    notes               text,
    placed_at           timestamptz NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz
);
COMMENT ON TABLE shop.orders IS 'Customer orders. About 1% of customers own about 30% of rows (planted problem P01). RLS: filtered by tenant_id.';
COMMENT ON COLUMN shop.orders.placed_at IS 'When the customer placed the order; seeded data covers 2024-01-01 to 2026-09-30.';
COMMENT ON COLUMN shop.orders.total_amount IS 'subtotal + tax + shipping - discount.';

CREATE TABLE shop.order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint NOT NULL REFERENCES shop.orders (order_id),
    product_id    int NOT NULL REFERENCES shop.products (product_id),
    variant_id    bigint NOT NULL REFERENCES shop.product_variants (variant_id),
    quantity      int NOT NULL CHECK (quantity > 0),
    unit_price    numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    discount      numeric(10, 2) NOT NULL DEFAULT 0,
    line_total    numeric(12, 2) NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.order_items IS 'Order lines. product_id is a foreign key with NO index (planted problem P02). Not covered by RLS: a known gap, as in many real systems.';

CREATE TABLE shop.payments (
    payment_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         int NOT NULL REFERENCES shop.tenants (tenant_id),
    order_id          bigint NOT NULL REFERENCES shop.orders (order_id),
    payment_method_id smallint NOT NULL REFERENCES shop.payment_methods (payment_method_id),
    amount            numeric(12, 2) NOT NULL CHECK (amount >= 0),
    currency_code     char(3) NOT NULL REFERENCES shop.currencies (currency_code),
    status            text NOT NULL CHECK (status IN ('pending', 'authorized', 'captured', 'failed', 'refunded')),
    provider_ref      text,
    paid_at           timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.payments IS 'Payment attempts for orders. RLS: filtered by tenant_id.';

CREATE TABLE shop.shipments (
    shipment_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES shop.orders (order_id),
    warehouse_id    smallint NOT NULL REFERENCES shop.warehouses (warehouse_id),
    carrier         text NOT NULL,
    tracking_number text,
    status          text NOT NULL CHECK (status IN ('pending', 'in_transit', 'delivered', 'returned')),
    shipped_at      timestamptz,
    delivered_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.shipments IS 'Parcels sent from a warehouse. An order can have several shipments.';

CREATE TABLE shop.shipment_items (
    shipment_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id      bigint NOT NULL REFERENCES shop.shipments (shipment_id),
    order_item_id    bigint NOT NULL REFERENCES shop.order_items (order_item_id),
    quantity         int NOT NULL CHECK (quantity > 0)
);
COMMENT ON TABLE shop.shipment_items IS 'Which order lines (and how many units) are in which shipment.';

CREATE TABLE shop.invoices (
    invoice_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       bigint NOT NULL UNIQUE REFERENCES shop.orders (order_id),
    invoice_number text NOT NULL UNIQUE,
    status         text NOT NULL CHECK (status IN ('draft', 'issued', 'paid', 'void')),
    total_amount   numeric(12, 2) NOT NULL,
    issued_at      timestamptz,
    due_at         timestamptz
);
COMMENT ON TABLE shop.invoices IS 'One invoice per order. invoice_number comes from the get_next_invoice_number routine.';

CREATE TABLE shop.refunds (
    refund_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   bigint NOT NULL REFERENCES shop.orders (order_id),
    payment_id bigint NOT NULL REFERENCES shop.payments (payment_id),
    amount     numeric(12, 2) NOT NULL CHECK (amount > 0),
    reason     text,
    status     text NOT NULL CHECK (status IN ('requested', 'approved', 'processed', 'rejected')),
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.refunds IS 'Money returned to customers, linked to the original payment.';
