-- 040_append_partitioned.sql
-- Append-heavy tables: stock levels, stock movements, the partitioned audit log, price history.

SET ROLE shop_owner;

CREATE TABLE shop.inventory (
    warehouse_id     smallint NOT NULL REFERENCES shop.warehouses (warehouse_id),
    variant_id       bigint NOT NULL REFERENCES shop.product_variants (variant_id),
    quantity_on_hand int NOT NULL CHECK (quantity_on_hand >= 0),
    quantity_reserved int NOT NULL DEFAULT 0 CHECK (quantity_reserved >= 0),
    reorder_point    int NOT NULL DEFAULT 10,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (warehouse_id, variant_id)
);
COMMENT ON TABLE shop.inventory IS 'Current stock per warehouse and variant. Popular variants are updated by many orders at once (hot-row contention, planted problem P08).';

CREATE TABLE shop.inventory_movements (
    movement_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id   smallint NOT NULL REFERENCES shop.warehouses (warehouse_id),
    variant_id     bigint NOT NULL REFERENCES shop.product_variants (variant_id),
    movement_type  text NOT NULL CHECK (movement_type IN ('receipt', 'sale', 'adjustment', 'return', 'transfer')),
    quantity       int NOT NULL,
    reference_type text,
    reference_id   bigint,
    created_at     timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE shop.inventory_movements IS 'Ledger of every stock change. Append-only and large.';
COMMENT ON COLUMN shop.inventory_movements.quantity IS 'Signed: positive adds stock, negative removes it.';

-- The audit log is partitioned by month. The primary key must include the partition key (created_at).
-- Queries that do not filter on created_at scan every partition (planted problem P03).
CREATE TABLE shop.audit_log (
    audit_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL,
    tenant_id  int,
    table_name text NOT NULL,
    record_id  bigint NOT NULL,
    action     char(1) NOT NULL CHECK (action IN ('I', 'U', 'D')),
    changed_by text,
    old_data   jsonb,
    new_data   jsonb,
    PRIMARY KEY (audit_id, created_at)
) PARTITION BY RANGE (created_at);
COMMENT ON TABLE shop.audit_log IS 'Row-change history written by the audit triggers, partitioned by month on created_at. Partitions exist for 2024-01 to 2026-12 plus a default partition.';

-- One partition per month. The loop generates the CREATE TABLE statements instead of 36 hand-written ones.
DO $$
DECLARE
    month_start date;
BEGIN
    FOR month_start IN
        SELECT generate_series(date '2024-01-01', date '2026-12-01', interval '1 month')::date
    LOOP
        EXECUTE format(
            'CREATE TABLE shop.audit_log_%s PARTITION OF shop.audit_log FOR VALUES FROM (%L) TO (%L)',
            to_char(month_start, 'YYYY_MM'),
            month_start,
            (month_start + interval '1 month')::date
        );
    END LOOP;
END
$$;

-- Catch-all for rows outside the monthly ranges, so an insert never fails for a date reason.
CREATE TABLE shop.audit_log_default PARTITION OF shop.audit_log DEFAULT;

CREATE TABLE shop.price_history (
    price_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       int NOT NULL REFERENCES shop.products (product_id),
    old_price        numeric(10, 2),
    new_price        numeric(10, 2) NOT NULL,
    changed_at       timestamptz NOT NULL,
    changed_by       text
);
COMMENT ON TABLE shop.price_history IS 'Every product price change, newest last.';
