import re
from collections import defaultdict

from .domain import CONSTRAINT_LABEL, KIND_LABEL, VOLATILITY, Catalog


def _cell(text: str | None) -> str:
    """Make text safe inside a markdown table cell."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _flags(table: str, column: str, cat: Catalog) -> list[str]:
    flags = []
    for con in cat.constraints.get(table, []):
        cols = (con["columns"] or "").split(", ")
        if column not in cols:
            continue
        if con["kind"] == "p":
            flags.append("PK")
        elif con["kind"] == "f":
            flags.append(f"FK to {con['ref_table']}")
        elif con["kind"] == "u" and len(cols) == 1:
            flags.append("unique")
    return flags


def render_dictionary(cat: Catalog) -> str:
    out = [
        "# Data dictionary",
        "",
        "> Generated by `poetry run shopdb docs` from the live database catalog and its `COMMENT ON` text.",
        "> Do not edit by hand: change the comment (db/schema/*.sql or db/post_load/160_comments.sql) and regenerate.",
        "> Row counts are the planner's estimates (`pg_class.reltuples`) and depend on the size profile that is loaded.",
        "",
        "## Contents",
        "",
    ]
    base = [t for t in cat.tables if t["kind"] in ("r", "p")]
    views = [t for t in cat.tables if t["kind"] in ("v", "m")]
    out += [f"- Tables ({len(base)}): " + ", ".join(f"[{t['name']}](#{t['name']})" for t in base)]
    out += [f"- Views ({len(views)}): " + ", ".join(f"[{t['name']}](#{t['name']})" for t in views)]
    out += [
        f"- [Routines](#routines) ({len(cat.routines)})",
        "- [Row-level security](#row-level-security)",
        "",
    ]

    for t in cat.tables:
        name = t["name"]
        out += [f"## {name}", ""]
        meta = [KIND_LABEL[t["kind"]]]
        if t["kind"] in ("r", "p", "m"):
            meta.append(f"about {t['approx_rows']:,} rows")
        if t["partitions"]:
            meta.append(f"{t['partitions']} partitions")
        if t["rls"]:
            meta.append("row-level security on")
        out += [f"*{', '.join(meta)}*", "", t["comment"] or "(no description)", ""]

        out += [
            "| Column | Type | Null | Default | Notes | Description |",
            "|---|---|---|---|---|---|",
        ]
        for col in cat.columns[name]:
            default = col["default_expr"] or ("identity" if col["identity"] else "")
            if len(default) > 40:
                default = default[:37] + "..."
            notes = ", ".join(_flags(name, col["name"], cat))
            out.append(
                f"| `{col['name']}` | {_cell(col['type'])} | {'' if col['not_null'] else 'yes'} "
                f"| {('`' + _cell(default) + '`') if default else ''} | {_cell(notes)} | {_cell(col['comment'])} |"
            )
        out.append("")

        checks = [
            c
            for c in cat.constraints.get(name, [])
            if c["kind"] in ("u", "c", "x") or (c["kind"] == "f")
        ]
        if checks:
            out += ["Constraints:", ""]
            out += [
                f"- `{c['name']}`: {CONSTRAINT_LABEL[c['kind']]} - `{_cell(c['definition'])}`"
                for c in checks
            ]
            out.append("")
        if cat.indexes.get(name):
            out += ["Indexes (besides the primary key):", ""]
            out += [f"- `{i['name']}`: `{_cell(i['definition'])}`" for i in cat.indexes[name]]
            out.append("")
        if cat.triggers.get(name):
            out += ["Triggers:", ""]
            out += [f"- `{tr['name']}`: `{_cell(tr['definition'])}`" for tr in cat.triggers[name]]
            out.append("")

    out += [
        "## Routines",
        "",
        "Functions and procedures of the `shop` schema. *definer* means SECURITY DEFINER: it runs with its owner's",
        "privileges (and therefore bypasses row-level security); invoker routines run as the caller.",
        "",
        "| Name | Kind | Arguments | Returns | Runs as | Volatility | Description |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in cat.routines:
        out.append(
            f"| `{r['name']}` | {'procedure' if r['kind'] == 'p' else 'function'} | `{_cell(r['args'])}` "
            f"| {('`' + _cell(r['result']) + '`') if r['kind'] == 'f' else ''} "
            f"| {'definer' if r['definer'] else 'invoker'} | {VOLATILITY[r['volatility']]} | {_cell(r['comment'])} |"
        )
    out.append("")

    out += [
        "## Row-level security",
        "",
        "Policies filter rows by `current_setting('app.tenant_id')`. The `mcp_*` roles default to tenant 1.",
        "",
        "| Table | Policy | Command | Roles | USING |",
        "|---|---|---|---|---|",
    ]
    for rows in cat.policies.values():
        for p in rows:
            out.append(
                f"| {p['tbl']} | {p['name']} | {p['cmd']} | {_cell(p['roles'])} | `{_cell(p['qual'])}` |"
            )
    out.append("")
    return "\n".join(out)


def _mermaid_type(sql_type: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^A-Za-z0-9]", "_", sql_type)).strip("_")


def render_erd(cat: Catalog) -> str:
    """A Mermaid entity-relationship diagram: every table with its key columns, and every foreign key."""
    tables = {t["name"] for t in cat.tables if t["kind"] in ("r", "p")}
    not_null = {(c["tbl"], c["name"]): c["not_null"] for cols in cat.columns.values() for c in cols}
    types = {(c["tbl"], c["name"]): c["type"] for cols in cat.columns.values() for c in cols}

    fks = [
        c
        for cons in cat.constraints.values()
        for c in cons
        if c["kind"] == "f" and c["tbl"] in tables and c["ref_table"] in tables
    ]
    fk_columns: dict[str, set[str]] = defaultdict(set)
    for c in fks:
        fk_columns[c["tbl"]].update(c["columns"].split(", "))

    lines = ["erDiagram"]
    for fk in sorted(fks, key=lambda c: (c["ref_table"], c["tbl"], c["columns"])):
        optional = not all(not_null[(fk["tbl"], col)] for col in fk["columns"].split(", "))
        parent_side = "|o" if optional else "||"
        lines.append(f'    {fk["ref_table"]} {parent_side}--o{{ {fk["tbl"]} : "{fk["columns"]}"')

    for name in sorted(tables):
        pk_cols: set[str] = set()
        for c in cat.constraints.get(name, []):
            if c["kind"] == "p":
                pk_cols.update(c["columns"].split(", "))
        shown = [
            col["name"] for col in cat.columns[name] if col["name"] in pk_cols | fk_columns[name]
        ]
        lines.append(f"    {name} {{")
        for col in shown:
            tag = "PK" if col in pk_cols else "FK"
            if col in pk_cols and col in fk_columns[name]:
                tag = "PK, FK"
            lines.append(f"        {_mermaid_type(types[(name, col)])} {col} {tag}")
        lines.append("    }")

    standalone = sorted(t for t in tables if not any(t in (c["tbl"], c["ref_table"]) for c in fks))
    body = "\n".join(lines)
    notes = ""
    if standalone:
        names = ", ".join(f"`{t}`" for t in standalone)
        verb = "has" if len(standalone) == 1 else "have"
        notes = f"\nNo foreign keys to or from other tables: {names} {verb} none by design"
        if "audit_log" in standalone:
            notes += " (`audit_log` points at rows by table name and id, so the audit trail survives deletes)"
        notes += ".\n"
    return (
        "# Entity-relationship diagram\n\n"
        "> Generated by `poetry run shopdb docs` from the foreign keys in the live database. Do not edit by hand.\n"
        "> Only key columns are shown; all columns are in [data-dictionary.md](data-dictionary.md).\n"
        "> Reading the lines: `A ||--o{ B` means one A has zero or more B; `|o` on the left means the parent is optional (nullable foreign key).\n\n"
        f"```mermaid\n{body}\n```\n{notes}\n"
    )


def generate(catalog_reader, writer):
    cat = catalog_reader()
    return [
        writer(name, text)
        for name, text in (
            ("data-dictionary.md", render_dictionary(cat)),
            ("erd.md", render_erd(cat)),
        )
    ]
